server:
  port: 3000
  servlet.context-path: /skn-lms-fabrics

info:
  app:
    name: ${spring.application.name}
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java.version: '@java.version@'

# Swagger : `http://localhost:3000/skn-lms-fabrics/swagger-ui/index.html`
management:
  endpoints:
    enabled-by-default: false
    jmx.exposure:
        exclude: '*'
        include: health, info
    web.exposure.include: health, info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always

server.tomcat.relaxed-query-chars: "|,{,},[,]"

spring:
  # Spring JDBC configuration
  datasource:
    url: jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
    username: ${mysql.service.username}
    password: ${mysql.service.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: false
    open-in-view: false
    properties:
      jakarta.persistence.validation.mode: none
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true #@TODO : Should Be False, use JOIN-FETCH
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: update #none

mysql:
  service:
    host: "localhost"
    port: 3306
    database: "catalog_service"
    username: "root"
    password: "root"
